version: "3"

services:
    hivegame:
        build:
            context: ./app
        ports:
            - "8080:80"
        depends_on:
            - database
        command: php -S 0.0.0.0:80

    database:
        build:
            context: ./database
        ports:
            - "3307:3306"
        environment:
            - MYSQL_HOST=${DB_HOST}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin:lts
        ports: 
            - 8000:80
        environment:
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: ${DB_ROOT_PASSWORD}
        depends_on:
            - database

    jenkins:
        image: jenkins/jenkins:lts
        ports:
            - "8081:8080"
            - "50000:50000"
        volumes:
            - jenkins-data:/var/jenkins_home

    sonarqube:
        image: sonarqube:lts
        ports:
            - "9000:9000"
        volumes:
            - sonarqube-data:/opt/sonarqube/data

volumes:
    db-data:
    jenkins-data:
    sonarqube-data: