version: "3"

services:
    hivegame:
        build:
            context: ./game
        ports:
            - "8080:80"
        depends_on:
            - database
        command: php -S 0.0.0.0:80

    database:
        build:
            context: ./database
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=hive
            - MYSQL_ROOT_PASSWORD=root            
            - MYSQL_USER=hiveuser
            - MYSQL_PASSWORD=hivepassword
        volumes:
            - db-data:/var/lib/mysql
    
    phpmyadmin:
        image: phpmyadmin
        ports: 
            - 8000:80
        environment:
            PMA_HOST: database
            PMA_USER: hiveuser
            PMA_PASSWORD: hivepassword
        depends_on:
            - database

volumes:
    db-data: